config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :todos do
    member do
      patch :checked
    end
  end
  root "todos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates_presence_of :title, :due_date, :description 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, :only => [:show, :edit, :update, :destroy, :checked]

  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to todos_url
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @todo.update_attributes(todo_params)
      redirect_to todos_path(@todo)
    else
      render :edit
    end
  end
  def destroy
    @todo.destroy
    redirect_to todos_url
  end
  def checked
    if @todo.check_box == false
      @todo.update_attribute(:check_box, true)
    else
      @todo.update_attribute(:check_box, false)
    end
    redirect_to todos_path(@todo)
  end

  private
  def set_todo
    @todo = Todo.find(params[:id])
  end
  def todo_params
    params.require(:todo).permit(:title, :due_date, :description, :check_box)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<% if @todo.errors.present? %>
  <ul>
    <% @todo.errors.each do |error, message|%>
      <li><%="#{error.capitalize} #{message}"%></li>
    <% end %>
  </ul>
<% end %>

<div class="form container">
  <%= form_for @todo do |f| %>
    <div class="form-group">
      <%= f.label :title, "Task" %>
      <%= f.text_field :title,class: "form-control"  %>
    </div>
    <div class="form-group">
      <%= f.label :due_date, "Expired Date" %>
      <%= f.text_field :due_date,class: "form-control"  %>
    </div>
    <div class="form-group">
      <%=f.label :description, "Description" %>
      <%= f.text_area :description,class: "form-control" %>
    </div>
    <%= f.submit %>
  <%end%>
</div>

app/views/todos/edit.html.erb
<%= render :partial => "form" %>

app/views/todos/index.html.erb
<h1> My Todo List</h1>

<table class="table table-striped table-condensed">
  <tr>
    <td>Status</td>
    <td>Matter</td>
    <td>Started from</td>
    <td>Expired by</td>
    <td>Note</td>
    <td>Edit</td>
    <td>Delete</td>
  </tr>
  <% @todos.each do |todo| %>
  <tr>
      <% if todo.check_box %>
        <td>
          <%= link_to checked_todo_path(todo), method: :patch do %>
            <span class="glyphicon glyphicon-ok"></span>
          <% end %>
        </td>
      <% else %>
        <td>
          <%= link_to checked_todo_path(todo), method: :patch do %>
            <span class="glyphicon glyphicon-unchecked"></span>
          <% end %>
      <% end %>
    </td>
    <td><%= todo.title %></td>
    <td><%= todo.created_at.time.strftime("%Y-%m-%d")%></td>
    <td><%= todo.due_date%></td>
    <td><%= todo.description%></td>
    <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
    <% if Time.now.to_date <= todo.due_date %>
      <td><%= link_to 'Delete', todo_path(todo), method: :delete, data:{confirm: "Are you sure?"}%></td>
    <% else %>
      <td>EXPIRED</td>
    <% end %>
  </tr>
  <% end %>
</table>
<%= link_to 'New Todo', new_todo_path %>

app/views/todos/new.html.erb
<%= render :partial => "form" %>

app/views/todos/show.html.erb
<%= @todo.title%>
<%= @todo.created_at%>
<%= simple_format(@todo.description)%>
<%= link_to 'Back to index', todos_path%>